#165273424 Setup redux
andela/ah-frontend-invictus pull request #4
Opened 2019-05-28 04:54 UTC by joelmugaya

#### What does this PR do?
- Setup redux

#### Description of Task to be completed
- install redux, react-redux & redux-thunk
- create a store
- update App.js to use redux
- create a file structure

#### How should this be manually tested?
- A redux folder with a store and reducer has been added to the file structure

#### What are the relevant pivotal tracker stories?
- [#165273424](https://www.pivotaltracker.com/story/show/165273424)

2019-05-28 06:55 UTC, sanya-kenneth approved these changes

2019-05-28 07:30 UTC, engjames approved these changes
Nice work @joelmugaya

2019-05-28 07:35 UTC, 3Nakajugo approved these changes

2019-05-29 09:09 UTC, njeri-ngigi requested changes

2019-05-29 09:09 UTC, njeri-ngigi commented on src/App.js
> +function App() {
Please use a class here that extends Component

2019-05-29 09:09 UTC, njeri-ngigi commented on src/App.js
> +function App() {
Also use the render() method

2019-05-29 09:14 UTC, njeri-ngigi approved these changes

2019-05-29 09:14 UTC, merged